# Generated by Django 5.0.2 on 2024-02-28 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_remove_unique_order_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='positive_sale_debt',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(check=models.Q(('debt__gte', 0)), name='positive_sale_debt', violation_error_message='Amount paid cannot be greater than potential revenue for this sale. Try adjusting the sale price or quantity.'),
        ),
    ]
